import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"
import { ThemeProvider } from "@/components/theme-provider";
import { CartProvider } from "@/components/cart-provider";
import Header from "@/components/header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className={"inter.className"}>
      <AppRouterCacheProvider>
        <ThemeProvider>
          <CartProvider>
            <Header />
            <main style={{ minHeight: "100vh", paddingTop: "64px" }}>{children}</main>
          </CartProvider>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </body>
  </html>
  );
}
